# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-12 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20180712_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_data',
            name='msg',
            field=models.CharField(default='None', max_length=254),
        ),
    ]
