# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-13 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20180712_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_data',
            name='image',
            field=models.ImageField(upload_to='pictures'),
        ),
    ]
