# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-14 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20180714_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_data',
            name='msg',
            field=models.CharField(default='', max_length=254),
        ),
    ]
