# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-14 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_delete_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=20)),
                ('friend_name', models.CharField(max_length=20)),
            ],
        ),
    ]
